all: string function_overloading dynamic_array

string: string.cc
	g++ -o string string.cc

function_overloading: function_overloading.cc
	g++ -o function_overloading function_overloading.cc

dynamic_array: dynamic_array.cc
	g++ -o dynamic_array dynamic_array.cc

clean:
	rm string function_overloading dynamic_array
