all: array_pointer call_by_reference

array_pointer: array_pointer.cc
	g++ -o array_pointer array_pointer.cc

call_by_reference: call_by_reference.cc
	g++ -o call_by_reference call_by_reference.cc

clean:
	rm array_pointer call_by_reference
