all: min_max_sum rotate_integer

min_max_sum: min_max_sum.cc
	g++ -o min_max_sum min_max_sum.cc

rotate_integer: rotate_integer.cc
	g++ -o rotate_integer rotate_integer.cc

clean:
	rm min_max_sum rotate_integer
