version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: install cmake
          command: apt-get update && apt-get install -y cmake
      - run:
          name: install g++
          command: apt-get update && apt-get install -y g++
      - run:
          name: g++ version check
          command: echo `g++ --version`
      - run:
          name: make all
          command: |
            for dirname in hw*; do
              echo $dirname;
              cd $dirname;
              if [ -f "Makefile" ]; then
                make;
              else
                mkdir build;
                pushd build;
                cmake ..;
                make;
                popd;
              fi;
              cd ..;
            done;
