all: get_sum_diff to_lower_upper

get_sum_diff: get_sum_diff.cc
	g++ -o get_sum_diff get_sum_diff.cc

to_lower_upper: to_lower_upper.cc
	g++ -o to_lower_upper to_lower_upper.cc

clean:
	rm get_sum_diff to_lower_upper

