all: array_2dim touch_points cal_complex

array_2dim: array_2dim.cc
	g++ -o array_2dim array_2dim.cc

touch_points: touch_points.cc
	g++ -o touch_points touch_points.cc

cal_complex: cal_complex.cc
	g++ -o cal_complex cal_complex.cc

clean:
	rm array_2dim touch_points cal_complex
