all: struct_person array_struct_person array_struct_point

struct_person: struct_person.cc
	g++ -o struct_person struct_person.cc

array_struct_person: array_struct_person.cc
	g++ -o array_struct_person array_struct_person.cc

array_struct_point: array_struct_point.cc
	g++ -o array_struct_point array_struct_point.cc

clean:
	rm struct_person array_struct_person array_struct_point
